FROM openjdk:17-jdk-oraclelinux8

WORKDIR /docker-api

ENV HTTP_PORT="8085" \
    DATABASE_URL="jdbc:mysql://localhost:3306/immobile" \
    DATABASE_USERNAME="root" \
    DATABASE_PASSWORD="123456"

COPY target/*.jar /docker-api/app.jar

CMD ["java", "-jar", "/docker-api/app.jar"]

RUN echo "\n Imagem gerada com sucesso! \n"
