version: "3.1"

services:
  api-docker:
    container_name: api-docker
    image: api-docker-image
    restart: always
    environment:
      - HTTP_PORT=8085
      - DATABASE_URL=jdbc:postgresql://postgresql-container:5432/immobile
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
    ports:
      - "8085:8085"
    depends_on:
      - postgresql-service
    networks:
      - api-docker-db-network

  postgresql-service:
    container_name: postgresql-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: immobile
    ports:
      - "5432:5432"
    networks:
      - api-docker-db-network
    volumes:
      - api-docker-db-volume:/var/lib/postgresql/data

networks:
  api-docker-db-network:
    driver: bridge

volumes:
  api-docker-db-volume:
